project:
  type: website

website:
  title: "Angelo Desiderio"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual